TOKENS = [

    ('NUM', r'\d+'),
    ('STRING', r'"[^"]*"'),
    
    ('ASSIGN', r':='),
    ('PLUS', r'\+'),
    ('MINUS', r'-'),
    ('MULT', r'\*'),
    ('DIV', r'/'),
    ('MODULO', r'%'),
    ('READINT', r'readint'),
    ('READSTR', r'readstr'),
    ('LENGTH', r'length'),
    ('POSITION', r'position'),
    ('CONCATENATE', r'concatenate'),
    ('SUBSTRING', r'substring'),
    ('EQUALS', r'=='),
    ('NOT_EQUALS', r'!='),
    ('AND', r'and'),
    ('OR', r'or'),
    ('NOT', r'not'),
    ('TRUE', r'true'),
    ('FALSE', r'false'),
    ('LPAREN', r'\('),
    ('RPAREN', r'\)'),
    ('COMMA', r','),
    ('SEMICOLON', r';'),
    ('COLON', r':'),
    ('IF', r'if'),
    ('THEN', r'then'),
    ('ELSE', r'else'),
    ('FOR', r'for'),
    ('TO', r'to'),
    ('DO', r'do'),
    ('BEGIN', r'begin'),
    ('END', r'end'),
    ('PRINT', r'PRINT'),
    ('BREAK', r'break'),
    ('CONTINUE', r'continue'),
    ('EXIT', r'exit'),
    ('NUM_REL', r'=|<>|<|>|<=|>='),
    ('STR_REL', r'==|!='),
    ('IDENT', r'[a-zA-Z_]\w*'),
]
